# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_shop_info',
            fields=[
                ('shopID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('shopName', models.CharField(default=b'', max_length=200)),
                ('shopLogo', models.CharField(default=b'', max_length=1000)),
                ('province', models.CharField(default=b'', max_length=20)),
                ('city', models.CharField(default=b'', max_length=100)),
                ('adminRegion', models.CharField(default=b'', max_length=100)),
                ('businessArea', models.CharField(default=b'', max_length=100)),
                ('address', models.CharField(default=b'', max_length=200)),
                ('position', models.CharField(default=b'', max_length=100)),
                ('mapAddr', models.CharField(default=b'', max_length=200)),
                ('telephone', models.CharField(default=b'', max_length=100)),
                ('businessTime', models.CharField(default=b'', max_length=200)),
                ('avgPrice', models.DecimalField(decimal_places=1, default=b'0', max_digits=10)),
                ('isHllShop', models.CharField(default=b'', max_length=20)),
                ('hllShopID', models.CharField(default=b'', max_length=20)),
                ('hllShopName', models.CharField(default=b'', max_length=200)),
                ('relCompany', models.CharField(default=b'', max_length=200)),
                ('createStamp', models.CharField(default=b'', max_length=200)),
                ('actionStamp', models.CharField(default=b'', max_length=200)),
            ],
        ),
    ]
